### ISSUE TITLE
Get rid of ugly Sidebery top menu

### ISSUE THREAD

**Issue by NotAF0e** [lewisHeart/Floorp-Configs#3]
![image](https://github.com/lewisHeart/Floorp-Configs/assets/75176016/64824a7b-adb6-4a63-98bf-8a8499a91da3)

Is there a specific option i can enable to remove this as I want to use keyboard shortcuts instead, thanks.
Other than that this config is great man!

**Comment by lewisHeart** [comment]
In the tutorial I explain how to do this, just go to:

Design about:preferences#design -> Tab Bar Style -> Collapse Tree Style Tab

![a](https://github.com/lewisHeart/Floorp-Configs/assets/32145272/2b65d0c8-0dfb-4529-b812-2a3e7dfd8664)

**Comment by notaf0e** [comment]
Ah thanks silly me
